services:
  - type: web
    name: studiz-server
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: studiz-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: studiz-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: studiz-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: studiz-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: studiz-postgres
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: studiz-postgres
    databaseName: studiz
    user: studiz
    plan: free
    postgresMajorVersion: 15

